### ISSUE TITLE
Unclear on how to install the dependencies and run the server 

### ISSUE THREAD

**Issue by shadownerd77** [gragland/chatgpt-chrome-extension#2]
Could you provide more details on the first and second step of getting this extension to work it would be helpful for non technical folks as i am struggling.

**Comment by gragland** [comment]
After downloading this project to your computer you'll need to navigate to the project directory in a terminal window and run those commands. A code editor like VS Code may be helpful here as it includes a terminal and also will show the hidden files (.env and .env.example) that are needed (see updated instructions). Sorry it's a bit technical at the moment because of the local server that's required.
